// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_akQBsUw6d_KJ5xda7ktwCbnRxAXPM6Q',
    appId: '1:977324511916:web:2fe3b5737206765b4d0509',
    messagingSenderId: '977324511916',
    projectId: 'doctorstime-45056',
    authDomain: 'doctorstime-45056.firebaseapp.com',
    storageBucket: 'doctorstime-45056.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMAlW4oz-sA3M22vuxbxAqg0gZXHeqJXg',
    appId: '1:977324511916:android:216dc098b75bc1f44d0509',
    messagingSenderId: '977324511916',
    projectId: 'doctorstime-45056',
    storageBucket: 'doctorstime-45056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvqYxtGVEqiR1Qjot9F6Sgq7caxna46xo',
    appId: '1:977324511916:ios:0cdf8485823bd11a4d0509',
    messagingSenderId: '977324511916',
    projectId: 'doctorstime-45056',
    storageBucket: 'doctorstime-45056.appspot.com',
    iosBundleId: 'com.example.doctorsTime',
  );
}
